// Tests for the CUE -> build_spec.zig pipeline.
//
// build_spec.zig is generated by gen_build_spec.sh from project.cue. These
// tests assert the invariants build.zig relies on when it walks the module
// graph, so a malformed export fails here rather than as a confusing build
// error later.

const std = @import("std");
const testing = std.testing;

const spec = @import("build_spec.zig");
const compat = @import("compat.zig");

// --- shape -----------------------------------------------------------------

test "spec declares at least one module" {
    try testing.expect(spec.modules.len > 0);
}

test "spec declares supported Zig toolchain lanes" {
    try testing.expect(spec.toolchain.zig_lanes.len > 0);

    var preferred_found = false;
    for (spec.toolchain.zig_lanes) |lane| {
        try testing.expect(lane.len == 4);
        try testing.expect(std.mem.startsWith(u8, lane, "0."));
        if (std.mem.eql(u8, lane, spec.toolchain.preferred_zig_lane)) {
            preferred_found = true;
        }
    }
    try testing.expect(preferred_found);
}

test "package declarations are well-formed" {
    for (spec.packages) |pkg| {
        try testing.expect(pkg.name.len > 0);
        try testing.expect(pkg.url != null or pkg.path != null);
        if (pkg.hash) |hash| try testing.expect(hash.len > 0);
    }
}

test "build options are unique and typed" {
    for (spec.options, 0..) |a, i| {
        try testing.expect(a.name.len > 0);
        for (spec.options[i + 1 ..]) |b| {
            try testing.expect(!std.mem.eql(u8, a.name, b.name));
        }
        switch (a.type) {
            .bool => if (a.bool_default) |_| {} else {},
            .string => if (a.string_default) |v| try testing.expect(v.len >= 0),
            .u32 => if (a.u32_default) |_| {} else {},
        }
    }
}

test "every module has a non-empty name and root" {
    for (spec.modules) |m| {
        try testing.expect(m.name.len > 0);
        try testing.expect(m.root.len > 0);
    }
}

test "every root path ends in .zig" {
    for (spec.modules) |m| {
        try testing.expect(std.mem.endsWith(u8, m.root, ".zig"));
    }
}

test "post-build commands have argv" {
    for (spec.modules) |m| {
        for (m.pre) |cmd| {
            try testing.expect(cmd.argv.len > 0);
            for (cmd.argv) |arg| try testing.expect(arg.len > 0);
        }
        for (m.post) |cmd| {
            try testing.expect(cmd.argv.len > 0);
            for (cmd.argv) |arg| try testing.expect(arg.len > 0);
        }
    }
}

test "package imports name an alias, package, and module" {
    for (spec.modules) |m| {
        for (m.pkg_imports) |pkg| {
            try testing.expect(pkg.alias.len > 0);
            try testing.expect(pkg.package.len > 0);
            try testing.expect(pkg.module.len > 0);
        }
        for (m.build_options) |option_name| {
            try testing.expect(option_name.len > 0);
            var found = false;
            for (spec.options) |option| {
                if (std.mem.eql(u8, option.name, option_name)) found = true;
            }
            try testing.expect(found);
        }
    }
}

test "module names are unique" {
    for (spec.modules, 0..) |a, i| {
        for (spec.modules[i + 1 ..]) |b| {
            try testing.expect(!std.mem.eql(u8, a.name, b.name));
        }
    }
}

// --- dependency graph ------------------------------------------------------

fn hasModule(name: []const u8) bool {
    for (spec.modules) |m| {
        if (std.mem.eql(u8, m.name, name)) return true;
    }
    return false;
}

test "every declared dependency resolves to a declared module" {
    // build.zig does `built.get(dep).?` — an unresolved dep panics there.
    for (spec.modules) |m| {
        for (m.deps) |dep| {
            try testing.expect(hasModule(dep));
        }
    }
}

test "no module depends on itself" {
    for (spec.modules) |m| {
        for (m.deps) |dep| {
            try testing.expect(!std.mem.eql(u8, m.name, dep));
        }
    }
}

test "dependency graph is acyclic" {
    // Kahn's algorithm over the declared edges. build.zig links libraries in
    // spec order, so a cycle would be unbuildable.
    var remaining: [spec.modules.len]bool = .{true} ** spec.modules.len;
    var resolved: usize = 0;

    var progress = true;
    while (progress) {
        progress = false;
        for (spec.modules, 0..) |m, i| {
            if (!remaining[i]) continue;

            var deps_met = true;
            for (m.deps) |dep| {
                for (spec.modules, 0..) |other, j| {
                    if (std.mem.eql(u8, other.name, dep) and remaining[j]) {
                        deps_met = false;
                    }
                }
            }

            if (deps_met) {
                remaining[i] = false;
                resolved += 1;
                progress = true;
            }
        }
    }

    try testing.expectEqual(spec.modules.len, resolved);
}

// --- source files on disk --------------------------------------------------

/// The 0.14/0.15/0.16 filesystem divergence lives in the compat adaptor.
fn rootExists(path: []const u8) bool {
    return compat.exists(compat.io(), path);
}

test "every module root exists on disk" {
    // The generator copies paths verbatim out of CUE; a typo there produces a
    // build failure with no pointer back to project.cue.
    for (spec.modules) |m| {
        if (!rootExists(m.root)) {
            std.debug.print("missing root for module '{s}': {s}\n", .{ m.name, m.root });
            return error.ModuleRootMissing;
        }
    }
}

// --- kind and optimize -----------------------------------------------------

test "exactly one executable is named app" {
    var exe_count: usize = 0;
    var found_app = false;
    for (spec.modules) |m| {
        if (m.kind == .exe) exe_count += 1;
        if (std.mem.eql(u8, m.name, "app")) {
            found_app = true;
            try testing.expectEqual(spec.Kind.exe, m.kind);
        }
    }
    try testing.expect(exe_count > 0);
    try testing.expect(found_app);
}

test "the release-profile module maps to ReleaseFast" {
    // project.cue marks only `app` as profile: "release".
    for (spec.modules) |m| {
        if (std.mem.eql(u8, m.name, "app")) {
            try testing.expectEqual(std.builtin.OptimizeMode.ReleaseFast, m.optimize);
        }
    }
}

test "default-profile modules map to Debug" {
    for (spec.modules) |m| {
        if (std.mem.eql(u8, m.name, "core") or std.mem.eql(u8, m.name, "danzig")) {
            try testing.expectEqual(std.builtin.OptimizeMode.Debug, m.optimize);
        }
    }
}

test "non-executable modules are valid graph nodes" {
    for (spec.modules) |m| {
        switch (m.kind) {
            .exe => {},
            .static, .shared, .module => try testing.expect(m.deps.len >= 0),
        }
    }
}

// --- link mode -------------------------------------------------------------

test "shared modules are linked over the ABI" {
    // An import-consumed shared library is a contradiction: a .dylib/.so is an
    // ABI artifact. The schema forces link: "abi" for shared; assert it held.
    for (spec.modules) |m| {
        if (m.kind == .shared) try testing.expectEqual(spec.Link.abi, m.link);
    }
}

test "an import dependency resolves to a static module" {
    // build.zig only merges a dependency as a Zig module when it is a static
    // module marked link: "import". Exes and shared libs are never @imported.
    for (spec.modules) |m| {
        for (m.deps) |dep| {
            for (spec.modules) |d| {
                if (std.mem.eql(u8, d.name, dep) and d.link == .import) {
                    try testing.expect(d.kind == .static or d.kind == .module);
                }
            }
        }
    }
}

test "module-only targets are import edges" {
    for (spec.modules) |m| {
        if (m.kind == .module) {
            try testing.expectEqual(spec.Link.import, m.link);
        }
    }
}
